server:
  port: 8080
  servlet:
    context-path: /nike-shop

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/db_nike_shop}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:090203Qu@n}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        connection:
          characterEncoding: utf8mb4
          useUnicode: true
          charset: UTF-8
    show-sql: true
    generate-ddl: true
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:quandinh.09022003@gmail.com}
    password: rkhy dsrm znwu xjda
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        socketFactory:
          class: javax.net.ssl.SSLSocketFactory
          fallback: false
          port: 587
        ssl:
          trust: smtp.gmail.com
